### ISSUE TITLE
Large plots give `HTTP Error 413: Request Entity Too Large`

### ISSUE THREAD

**Issue by plutonium-239** [plutonium-239/plotlyshare#1]
Happens with large plots such as animations with multiple images etc., easy to reproduce.

Reason: Deta Base has a payload limit of 5MB [source](https://deta.space/docs/en/build/faq#why-am-i-encountering-http-error-413-entity-too-large-)

Fix: Check size and split into chunks if necessary

Error log:
```bash
[ERROR] 2024-04-06T18:46:33.465Z 62e74b20-7bec-4968-93e5-3edca21c95b0 Exception on /upload [POST]
Traceback (most recent call last):
File "/opt/python/flask/app.py", line 1463, in wsgi_app
response = self.full_dispatch_request()
File "/opt/python/flask/app.py", line 872, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/opt/python/flask/app.py", line 870, in full_dispatch_request
rv = self.dispatch_request()
File "/opt/python/flask/app.py", line 855, in dispatch_request
return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args) # type: ignore[no-any-return]
File "/var/task/main.py", line 40, in upload_plot
base.put({'html': html_text, 'name': name}, key)
File "/opt/python/deta/base.py", line 152, in put
code, res = self._request("/items", "PUT", {"items": [data]}, content_type=JSON_MIME)
File "/opt/python/deta/service.py", line 85, in _request
raise urllib.error.HTTPError(url, status, res.reason, res.headers, res.fp)
urllib.error.HTTPError: HTTP Error 413: Request Entity Too Large
```

**Comment by plutonium-239** [comment]
Implemented Fix: Add a Drive to store files larger than the 400KB limit for a Base row (yeah error message was the same as for 5mb payload limit but i found out the hard way) - no chunking done.
Present in v1.0.7 of the space app, live right now.
